name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build --tag bashbrew --pull .
          docker run --rm bashbrew tar -cC /usr/local/bin bashbrew | tar -xv
          ./bashbrew --version
      - name: Smoke Test
        run: |
          image='https://github.com/docker-library/official-images/raw/master/library/hello-world'
          ./bashbrew list "$image"
          ./bashbrew list --uniq "$image"
          ./bashbrew cat "$image"
